version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-jammy
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run:
          name: Run Playwright specs
          command: npm run test
