version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.29.0-focal
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Playwright specs
          command: npm run test
  build:
    jobs:
      - build