version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.15.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run:
          name: Run Playwright specs
          command: npm run test
